name: Injector Scan

on:
  push:
    branches: [ main ]
    paths:
      - 'src/injector/**'    
  pull_request:
    branches: [ main ]
    paths:
      - 'src/injector/**'
  schedule:
    - cron: '0 8 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build src/injector/ --file  src/injector/Dockerfile --tag injector:${{github.sha}}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: injector:${{ github.sha }}
